# pipeline
# cfg_pipeline.yml
---
documentation:
  description: Options (specifications) for the "pipeline" script.

  authors:
    - iglesias-suarez_fernando
    - solino-fernandez_breixo

  maintainer:
    - iglesias-suarez_fernando
    - solino-fernandez_breixo

  references:
    - acknow_project

  projects:
    - usmile


# Specifications
analysis       : 'single' # 'single': gridpoints individually; 
                          # 'concat': gridpoints contatenated into a 
                          #           single time-series; 
spcam_parents  : ['tbp','qbp','vbp','ps','solin','shflx','lhflx']
spcam_children : ['tphystnd','phq','prect','fsns','flns','fsnt','flnt']
# spcam_children : ['tphystnd','flnt']
# spcam_children : ['phq','flns']
pc_alphas      : [0.001,0.01,0.1]
independence_test : "parcorr"
#pc_alphas      : [0.01]
region         : [ [-90,90] , [0, 360] ] # Lons: 120, 118
lim_levels     : False # [950, 750] # False
target_levels  : [3.643, 54.595, 103.317, 197.908, 379.100, 524.687, 763.404, 859.534, 912.644, 957.485] # False
target_levels  :  False
output_folder  : "/work/bd1179/b309172/analysis/usmile/causality_convection/python/causalnncam/causal_links/"
plots_folder : "./deleteme/test_causal_links/test_plots"
#output_folder  : "./test_causal_links"
verbosity      : 0
output_file_pattern :
  single: "{var_name}_{level}_lat-{lat}_lon-{lon}_{ind_test}_{experiment}.obj"
  concat: "{var_name}_{level}_{lat1}-{lat2}_{lon1}-{lon2}_{ind_test}_{experiment}.obj"



# Aggregated analysis
# ===================
thresholds : [.3, .5]
plot_file_pattern : 
  single: "{var_name}_{level}_lat{lat}_lon{lon}_a{pc_alpha}_{ind_test}_{experiment}.png"
  concat: "{var_name}_{level}_{lat1}-{lat2}_{lon1}-{lon2}_a{pc_alpha}_{ind_test}_{experiment}.png"

# Neural Network configuration
# ============================

nn_type : "SingleNN"
# nn_type : "CausalSingleNN"
# nn_type : "all"
input_order : [qbp, tbp, vbp, ps, solin, shflx, lhflx]
input_order : [tbp, qbp, vbp, ps, solin, shflx, lhflx]
output_order : [phq, tphystnd, fsnt, fsns, flnt, flns, prect]

nn_output_path : delete_me_2/models

hidden_layers : [32, 32, 32]   # Arbitrary, I choose them because it's a small NN
activation : relu


# Training configuration
# ----------------------

train_data_folder : /work/bd1083/b309162/preprocessed_data
# Monthly data, for testing
train_data_fn : 002_train_1_month.nc
valid_data_fn : 000_valid_1_month.nc
# Yearly data
# train_data_fn : 002_train_1_year.nc
# valid_data_fn : 005_valid_1_year.nc
epochs : 4 # From 006_8col_pnas_exact.yml
epochs : 1 # For testing
train_verbose : 0 # Silent
train_verbose : 1 # Continuous update
# train_verbose : 2 # Summary on epoch
tensorboard_folder : tensorboard

# From Tom https://github.com/tbeucler/CBRAIN-CAM/tree/master/notebooks/tbeucler_devlog/UW_DATA
normalization_folder : /work/bd1179/b309198/causal_discovery/rasp-et-al/data
normalization_fn : 001_norm.nc

input_sub : mean # From 006_8col_pnas_exact.yml
input_div : maxrs # From 006_8col_pnas_exact.yml
out_scale_dict_folder : /work/bd1179/b309198/causal_discovery/rasp-et-al/CBRAIN-CAM/
out_scale_dict_fn : nn_config/scale_dicts/002_pnas_scaling.pkl # From 006_8col_pnas_exact.yml
batch_size : 1024

# Learning Rate Scheduler
init_lr : 0.001 # From train.py (default)
step_lr : 1 # From 006_8col_pnas_exact.yml
divide_lr : 5 # From train.py (default)

# Early Stopping
train_patience : 5 # TODO: This number was chosen arbitrarily
